### ISSUE TITLE
Improving sample compression and computation time for 1d KDE plots

### ISSUE THREAD

**Issue by lukashergt** [handley-lab/anesthetic#180]
For complicated posterior distributions I've often needed to crank up the `ncompress` value and then been frustrated with the computation time, so I've looked into ways of speeding things up. To that end I have timed two lines from the following piece of code from `kde_plot_1d` in `plot.py`:

```python
    x, w = sample_compression_1d(data, weights, ncompress)
    tik = time.time()
    kde = gaussian_kde(x, weights=w)
    print("        KDE time =", time.time() - tik)
    tok = time.time()
    p = kde(x)
    print("   sampling time =", time.time() - tok)
```

And this is what I got for a large dataset with over 100000 samples:

```out
        KDE time = 0.009744882583618164
   sampling time = 85.50073575973511
```

So, it turns out that very little time is spent on computing the KDE. Almost all is spent on evaluating the KDE at the sample points. This leads to a few important conclusions:
1) **The line `kde = gaussian_kde(x, weights=w)` is super fast and should always be run with _all_ sample points, not only with the compressed samples.** This will significantly improve the plotted posterior.
2) The line `p = kde(x)` can be easily parallelized using the `multiprocessing` package by replacing it with:
    ```python
        from multiprocessing import Pool
        x_i = np.array_split(x, nprocesses)
        pool = Pool(processes=nprocesses)
        p_i = pool.map(kde, x_i)
        p = np.concatenate(p_i)
    ```
3) The x-values for plotting don't actually need to come from the original sample points. We could simply create a `np.linspace` instead within appropriate bounds, e.g.:
    ```python
        minx, maxx = ax.get_xlim()
        x = np.linspace(minx, maxx, num_plot_samples)
        p = kde(x)
    ```
    `num_plot_samples` is then the number of plotting samples and can be significantly smaller (e.g. 1000 instead of 100000) than what has been used for `ncompress` without altering the appearance of the posterior.

&nbsp;

This leads me to the following questions:
* Is there a reason to prefer using the original sample points for plotting rather than a `linspace`?
* If we implement point 3, should we differentiate between `ncompress` and some `num_plot_samples` and set the default of `ncompress` to all samples and use a smaller number for `num_plot_samples`? Or should we basically drop the current use of `ncompress` and use the variable name for the number of plotting samples?
* Should I, as outlined in point 2, implement the (possibly optional) parallelization of the call of `p=kde(x)`?
  Or is this obsolete if we implement point 3 which will allow to stick to a small number of plotting samples anyhow?
* Any hunch in how far all of this would also apply to the 2d case?

**Comment by williamjameshandley** [comment]
I think it's a very good ideal to improve performance (both in speed and accuracy) of the KDE, as it's current state does leave something to be desired.

It's important note a couple of things though:
- the line `kde = gaussian_kde(x, weights=w)` should indeed be very fast, since this isn't calculating anything, merely constructing the kde object (i.e. copying the samples and weights into the object).
- the `kde(y)` computation itself will take time proportional to `len(x)*len(y)` (i.e. `ncompress*num_plot_samples`), if you think about how a naive kde is computed (which is indeed what the scipy `gaussian_kde` [does](https://github.com/scipy/scipy/blob/v1.7.1/scipy/stats/_stats.pyx#L693)).

Having said that, it does look like the most recent version of scipy.stats has now moved the kde computation into cython, so it may have improved performance considerably meaning the default I chose a while back of ncompress=1000 is now a little out-of-date and worth re-investigating.

>Is there a reason to prefer using the original sample points for plotting rather than a linspace?

I think this might have been motivated by the previous use of `fastkde`, which did have a performance uplift. If it's clear that this introduces artifacts, then I think we probably should move to an appropriately adjusted linspace. 
The question remains as to how to choose the limits of the linspace.

>If we implement point 3, should we differentiate between ncompress and some num_plot_samples and set the default of ncompress to all samples and use a smaller number for num_plot_samples? Or should we basically drop the current use of ncompress and use the variable name for the number of plotting samples?


>Should I, as outlined in point 2, implement the (possibly optional) parallelization of the call of p=kde(x)?
Or is this obsolete if we implement point 3 which will allow to stick to a small number of plotting samples anyhow?

Add this as an extra issue -- probably beyond the scope of this.

>Any hunch in how far all of this would also apply to the 2d case?

In 2D the use of compressed samples to define the tricontourf region is better motivated, since it is a much more efficient compression than the grid. I think consistency with this was probably what motivated doing the same for the 1D case, but there a linspace is probably more efficient.

**Comment by lukashergt** [comment]
> the `kde(y)` computation itself will take time proportional to `len(x)*len(y)` (i.e. `ncompress*num_plot_samples`)

The `kde()` computation indeed depends on both `len(x)` and `len(y)`, but for the accuracy (especially in 1d) it is important to note that the full `x` is much more important than a large `y`, as demonstrated [in these plots](https://github.com/williamjameshandley/anesthetic/pull/181#issuecomment-924572345) in #181. Indeed, when using the full `x` it basically doesn't matter anymore accuracy-wise whether `len(y)=1000` or `len(y)=100000`.

To better discuss speed issues I've done some timings of the `kde_plot_1d` and `kde_contour_plot_2d` functions with a simple, single 1d and 2d Gaussian plot respectively. I'm showing two plots, the first for a total sample set of length 10'000 and the second with a length of 100'000. The plots are showing the timings on the y-axis for different values of `ncompress` on the x-axis. The blue line uses the current master branch with version number `2.0.0-beta.10`. The orange line uses the "improve compression branch", i.e. the one corresponding to #181 that implements using the full `x` but only `ncompress` for `y`.

![timings for 10000 sample points](https://user-images.githubusercontent.com/18258042/135023828-fb082986-b14f-4caa-a5ab-0f50276a8180.png)

![timings for 100000 sample point](https://user-images.githubusercontent.com/18258042/135023863-8a11a69f-5510-49d1-9806-98c0a4686492.png)

The plots might be a bit misleading in that they only show the timings, not the accuracy. Comparing the blue 1d master line to the orange (or parallelised red) branch line, it actually isn't fair to compare timings at the same `ncompress` value. If you want high accuracy posteriors, then you'll have to go all the way up to `ncompress=100000` for the blue master line. For the orange branch line, on the other hand, you can stay at `ncompress=1000` with no visible loss in accuracy compared to `ncompress=100000`.
